RESTORE DATABASE [DWH_PRODUCTION] 
FROM DISK = N'C:\Backup\DWH_PRODUCTION_FullBackup_YYYY-MM-DD-HH-MM-SS.bak'
WITH 
    MOVE 'DWH_PRODUCTION_Data' TO 'C:\SQLData\DWH_PRODUCTION.mdf', 
    MOVE 'DWH_PRODUCTION_Log' TO 'C:\SQLLog\DWH_PRODUCTION.ldf',
    REPLACE, RECOVERY, STATS = 5;