DECLARE @date VARCHAR(20)
SELECT @date = REPLACE(CONVERT(VARCHAR(20), GETDATE(), 120), ':', '-')
BACKUP DATABASE [DWH_PRODUCTION] 
TO DISK = N'C:\Backup\DWH_PRODUCTION_FullBackup_' + @date + '.bak'
WITH NOFORMAT, NOINIT,  
     NAME = N'DWH_PRODUCTION-Full Database Backup', 
     SKIP, NOREWIND, NOUNLOAD, STATS = 10;
